name: Build Vapor image

on:

  workflow_dispatch:
    inputs:
      should_publish:
        description: 'Should the image be published?'
        type: boolean
        default: false
        required: false

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

    strategy:
      matrix:
        image:
          - { php: 8.1, name: php81}
          - { php: 8.2, name: php82}
          - { php: 8.3, name: php83}

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.5
        with:
          php-version: ${{ matrix.image.php }}
          extensions: curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, pdo_sqlite, bcmath, intl, gd, exif, iconv, json, ctype, mongodb, redis
          coverage: none
          tools: composer:v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker build -f ${{ matrix.image.name }}.Dockerfile -t vapor-${{ matrix.image.name }}:latest .

      - name: Tag image
        run: docker tag vapor-${{ matrix.image.name }}:latest treggats/vapor:${{ matrix.image.name }}

      - name: Publish image
        if:  ${{ github.event.inputs.should_publish == 'true' }}
        run: docker push treggats/vapor:${{ matrix.image.name }}
