name: Build Vapor image

on:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

    strategy:
      matrix:
        image:
          - { php: 8.1, name: php81}
          - { php: 8.2, name: php82}
          - { php: 8.3, name: php83}

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@2.27.1
        with:
          php-version: ${{ matrix.image.php }}
          extensions: curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, pdo_sqlite, bcmath, intl, gd, exif, iconv, json, ctype, mongodb, redis
          coverage: none
          tools: composer:v2

      - name: Build image
        run: bash build.sh ${{ matrix.image.name }}
